package in.nmaloth.payments.constants;

public enum ServiceResponse {

    //Card Validation
    OK("OK"),
    NO_ENTRY("NO_ENTRY"),
    STATUS("STATUS"),
    BLK("BLK"),
    TEMP_BLK("TEMP_BLK"),
    SUSPECT_FRAUD("SUSPECT_FRAUD"),
    FRAUD("FRAUD"),
    PICK_UP("PICK_UP"),
    PLASTIC_INVALID("PLASTIC_INVALID"),
    PLASTIC_ACT("PLASTIC_ACT"),
    TRANSACTION_TYPE("TRANSACTION_TYPE"),
    TERMINAL_TYPE("TERMINAL_TYPE"),
    PURCHASE_TYPE("PURCHASE_TYPE"),
    CASH_BACK("CASH_BACK"),
    INSTALLMENT("INSTALLMENT"),
    INTERNATIONAL("INTERNATIONAL"),
    ACCT_LIMIT("ACCT_LIMIT"),
    NO_PRODUCT("NO_PRODUCT"),
    CARD_LIMIT("CARD_LIMIT"),
    SYSTEM_ERROR("SYSTEM_ERROR"),
    EXPIRED_CARD("EXPIRED_CARD"),
    ENTRY_MODE("ENTRY_MODE"),
    CURRENCY_CONVERSION("CURRENCY_CONVERSION"),
    INVALID_INSTRUMENT("INVALID_INSTRUMENT"),
    MESSAGE_ERROR("MESSAGE_ERROR"),
    INVALID_CURRENCY_CODE("INVALID_CURRENCY_CODE"),
    INVALID_ACCOUNT("INVALID_ACCOUNT"),
    INCOMING_REJECT("INCOMING_REJECT"),
    INVALID_PIN("INVALID_PIN"),
    INVALID_CVV("INVALID_CVV"),
    INVALID_ARQC("INVALID_ARQC"),
    INVALID_CVV2("INVALID_CVV2"),
    INVALID_DCVV("INVALID_DCVV"),
    INVALID_CAVV("INVALID_CAVV"),
    EXCEED_PIN_TRIES("EXCEED_PIN_TRIES"),
    NOT_FOUND("NOT_FOUND"),
    INVALID_EXPIRY_DATE("INVALID_EXPIRY_DATE"),
    INVALID_SERVICE_CODE("INVALID_SERVICE_CODE"),
    INVALID_PIN_BLOCK_FORMAT("INVALID_PIN_BLOCK_FORMAT"),
    DCVV_NOT_SUPPORTED("DCVV_NOT_SUPPORTED"),
    INVALID_CHIP("INVALID_CHIP"),
    INVALID_IAD("INVALID_IAD"),
    INVALID_FALLBACK_MAG("INVALID_FALLBACK_MAG"),
    INVALID_CVM("INVALID_CVM"),
    BLOCKED_COUNTRY("BLOCKED_COUNTRY"),
    BLOCKED_CURRENCY("BLOCKED_CURRENCY"),
    BLOCKED_MCC("BLOCKED_MCC"),
    BLOCKED_PURCHASE_TYPE("BLOCKED_PURCHASE_TYPE"),
    BLOCKED_LIMIT_TYPE("BLOCKED_LIMIT_TYPE"),
    BLOCKED_BALANCE_TYPE("BLOCKED_BALANCE_TYPE"),
    BLOCKED_TRANSACTION_TYPE("BLOCKED_TRANSACTION_TYPE"),
    BLOCKED_TERMINAL_TYPE("BLOCKED_TERMINAL_TYPE"),
    BLOCKED_CVR("BLOCKED_CVR"),
    BLOCKED_TVR("BLOCKED_TVR"),
    INVALID_NAME("INVALID_NAME"),
    ADDRESS_VERIFICATION("ADDRESS_VERIFICATION"),
    KEY_NOT_FOUND("KEY_NOT_FOUND"),
    NOT_VALID_YET("NOT_VALID_YET")




    ;

    private String serviceResponse;

    ServiceResponse(String serviceResponse){
        this.serviceResponse = serviceResponse;
    }

    public String getServiceResponse(){
        return this.serviceResponse;
    }
}
